# Generated by Django 5.2.12 on 2026-05-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fatura", "0004_fatura_odeme_yontemi_alter_faturakalemi_urun"),
        ("gider", "0001_initial"),
        ("tahsilat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KasaHesabi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Kasa Adı")),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "acilis_bakiyesi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Açılış Bakiyesi",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Açıklama"
                    ),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kasa Hesabı",
                "verbose_name_plural": "Kasa Hesapları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="KasaHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("giris", "Giriş (Nakit Geldi)"),
                            ("cikis", "Çıkış (Nakit Gitti)"),
                        ],
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Tutar"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Belge No"
                    ),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                (
                    "fatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kasa_hareketleri",
                        to="fatura.fatura",
                        verbose_name="Fatura",
                    ),
                ),
                (
                    "gider",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kasa_hareketi",
                        to="gider.gider",
                        verbose_name="Gider",
                    ),
                ),
                (
                    "tahsilat",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kasa_hareketi",
                        to="tahsilat.tahsilat",
                        verbose_name="Tahsilat",
                    ),
                ),
                (
                    "kasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hareketler",
                        to="kasa.kasahesabi",
                        verbose_name="Kasa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kasa Hareketi",
                "verbose_name_plural": "Kasa Hareketleri",
                "ordering": ["-tarih", "-olusturuldu"],
            },
        ),
    ]
