# Generated by Django 6.0.2 on 2026-03-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CekSenet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[("alınan", "Alınan"), ("verilen", "Verilen")],
                        max_length=10,
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(max_length=50, verbose_name="Çek/Senet No"),
                ),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vade_tarihi", models.DateField(verbose_name="Vade Tarihi")),
                (
                    "kesildi_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kesildiği Tarih"
                    ),
                ),
                (
                    "banka_sube",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Banka/Şube"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("tahsil_edildi", "Tahsil Edildi"),
                            ("iade", "İade"),
                            ("protestolu", "Protestolu"),
                        ],
                        default="beklemede",
                        max_length=20,
                    ),
                ),
                ("notlar", models.TextField(blank=True)),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceksenets",
                        to="cari.cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çek/Senet",
                "verbose_name_plural": "Çek/Senetler",
                "ordering": ["vade_tarihi"],
            },
        ),
    ]
