# Generated by Django 6.0.2 on 2026-03-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(max_length=200, verbose_name="Unvan / Ad Soyad"),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("musteri", "Müşteri"),
                            ("tedarikci", "Tedarikçi"),
                            ("diger", "Diğer"),
                        ],
                        default="musteri",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi / TC No"
                    ),
                ),
                (
                    "vergi_dairesi",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                ("adres", models.TextField(blank=True, verbose_name="Adres")),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cari",
                "verbose_name_plural": "Cariler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="HesapHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Belge / Fatura No"
                    ),
                ),
                ("aciklama", models.CharField(max_length=300, verbose_name="Açıklama")),
                (
                    "hareket_tipi",
                    models.CharField(
                        choices=[
                            ("fatura", "Fatura"),
                            ("tahsilat", "Tahsilat"),
                            ("odeme", "Ödeme"),
                            ("iade", "İade"),
                            ("duzeltme", "Düzeltme"),
                            ("diger", "Diğer"),
                        ],
                        default="diger",
                        max_length=20,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                (
                    "borc",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Borç"
                    ),
                ),
                (
                    "alacak",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Alacak",
                    ),
                ),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hareketler",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesap Hareketi",
                "verbose_name_plural": "Hesap Hareketleri",
                "ordering": ["-tarih", "-olusturma_tarihi"],
            },
        ),
    ]
