# Generated by Django 6.0.2 on 2026-03-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiderKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Gider Kategorisi",
                "verbose_name_plural": "Gider Kategorileri",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Gider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("aciklama", models.CharField(max_length=255)),
                (
                    "kdv_haric_tutar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "kdv_orani",
                    models.SmallIntegerField(
                        choices=[
                            (0, "%0"),
                            (1, "%1"),
                            (8, "%8"),
                            (10, "%10"),
                            (20, "%20"),
                        ],
                        default=20,
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Belge/F atura No"
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("banka", "Banka"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                            ("diger", "Diğer"),
                        ],
                        default="nakit",
                        max_length=20,
                    ),
                ),
                ("notlar", models.TextField(blank=True)),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="giderler",
                        to="gider.giderkategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gider",
                "verbose_name_plural": "Giderler",
                "ordering": ["-tarih"],
            },
        ),
    ]
