# Generated by Django 5.2.12 on 2026-05-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="Ürün Kodu"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                (
                    "birim",
                    models.CharField(
                        default="Adet", max_length=20, verbose_name="Birim"
                    ),
                ),
                (
                    "kdv_orani",
                    models.IntegerField(
                        choices=[(0, "%0"), (1, "%1"), (10, "%10"), (20, "%20")],
                        default=20,
                        verbose_name="KDV Oranı (%)",
                    ),
                ),
                (
                    "satis_fiyati",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Satış Fiyatı",
                    ),
                ),
                (
                    "alis_fiyati",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Alış Fiyatı",
                    ),
                ),
                (
                    "min_stok",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Min. Stok",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("giris", "Giriş"),
                            ("cikis", "Çıkış"),
                            ("sayim", "Sayım Düzeltme"),
                        ],
                        max_length=10,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                (
                    "miktar",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Miktar"
                    ),
                ),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Birim Fiyat",
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Belge No"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hareketler",
                        to="stok.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
                "ordering": ["-tarih", "-olusturuldu"],
            },
        ),
    ]
