# Generated by Django 5.2.12 on 2026-05-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="degerleme_yontemi",
            field=models.CharField(
                choices=[
                    ("ortalama", "Ağırlıklı Ortalama (WAC)"),
                    ("fifo", "FIFO — İlk Giren İlk Çıkar"),
                ],
                default="ortalama",
                help_text="VUK Md.274 — Ağırlıklı Ortalama veya FIFO",
                max_length=10,
                verbose_name="Değerleme Yöntemi",
            ),
        ),
    ]
