# Generated by Django 6.0.2 on 2026-03-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankaEkstre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        upload_to="ekstreler/", verbose_name="Dosya (Excel/PDF)"
                    ),
                ),
                ("yukleme_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "donem_baslangic",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dönem Başlangıç"
                    ),
                ),
                (
                    "donem_bitis",
                    models.DateField(blank=True, null=True, verbose_name="Dönem Bitiş"),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                ("islendi", models.BooleanField(default=False, verbose_name="İşlendi")),
            ],
            options={
                "verbose_name": "Banka Ekstresi",
                "verbose_name_plural": "Banka Ekstreleri",
                "ordering": ["-yukleme_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="BankaHesabi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Hesap Adı")),
                (
                    "banka_adi",
                    models.CharField(max_length=100, verbose_name="Banka Adı"),
                ),
                (
                    "sube",
                    models.CharField(blank=True, max_length=100, verbose_name="Şube"),
                ),
                (
                    "hesap_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Hesap No / IBAN"
                    ),
                ),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Banka Hesabı",
                "verbose_name_plural": "Banka Hesapları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="BankaHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("islem_tarihi", models.DateField(verbose_name="İşlem Tarihi")),
                ("aciklama", models.CharField(max_length=400, verbose_name="Açıklama")),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Tutar"
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[("giris", "Giriş (+)"), ("cikis", "Çıkış (-)")],
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "referans_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referans No"
                    ),
                ),
                (
                    "eslesti",
                    models.BooleanField(default=False, verbose_name="Cari ile Eşleşti"),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banka_hareketleri",
                        to="cari.cari",
                        verbose_name="Eşleşen Cari",
                    ),
                ),
                (
                    "ekstre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hareketler",
                        to="banka.bankaekstre",
                        verbose_name="Ekstre",
                    ),
                ),
                (
                    "banka_hesabi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hareketler",
                        to="banka.bankahesabi",
                        verbose_name="Banka Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka Hareketi",
                "verbose_name_plural": "Banka Hareketleri",
                "ordering": ["-islem_tarihi"],
            },
        ),
        migrations.AddField(
            model_name="bankaekstre",
            name="banka_hesabi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ekstreler",
                to="banka.bankahesabi",
                verbose_name="Banka Hesabı",
            ),
        ),
    ]
