# Generated by Django 6.0.2 on 2026-03-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banka", "0001_initial"),
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tahsilat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("tahsilat", "Tahsilat (Gelen)"),
                            ("odeme", "Ödeme (Giden)"),
                        ],
                        default="tahsilat",
                        max_length=15,
                        verbose_name="Tip",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Tutar"
                    ),
                ),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("havale", "Havale / EFT"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                            ("senet", "Senet"),
                            ("diger", "Diğer"),
                        ],
                        default="havale",
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Makbuz / Belge No"
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "banka_hareketi",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tahsilat",
                        to="banka.bankahareketi",
                        verbose_name="Banka Hareketi",
                    ),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tahsilatlar",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat / Ödeme",
                "verbose_name_plural": "Tahsilatlar / Ödemeler",
                "ordering": ["-tarih", "-olusturma_tarihi"],
            },
        ),
    ]
