# Generated by Django 6.0.5 on 2026-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LisansBilgisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "install_tarihi",
                    models.DateField(auto_now_add=True, verbose_name="Kurulum Tarihi"),
                ),
                (
                    "lisans_tipi",
                    models.CharField(
                        choices=[
                            ("deneme", "Deneme (15 Gün)"),
                            ("standart", "Standart"),
                            ("premium", "Premium"),
                        ],
                        default="deneme",
                        max_length=20,
                        verbose_name="Lisans Tipi",
                    ),
                ),
                (
                    "lisans_anahtari",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Lisans Anahtarı"
                    ),
                ),
                (
                    "musteri_kodu",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Müşteri Kodu"
                    ),
                ),
                (
                    "lisans_bitis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lisans Bitiş Tarihi"
                    ),
                ),
                ("guncellendi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lisans Bilgisi",
                "verbose_name_plural": "Lisans Bilgileri",
            },
        ),
    ]
