# Generated by Django 6.0.5 on 2026-05-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lisans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lisansbilgisi",
            options={
                "ordering": ["-guncellendi"],
                "verbose_name": "Lisans Bilgisi",
                "verbose_name_plural": "Lisans Bilgileri",
            },
        ),
    ]
