# Generated by Django 6.0.2 on 2026-03-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fatura_no",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Fatura No"
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("satis", "Satış (Müşteriye)"),
                            ("alis", "Alış (Tedarikçiden)"),
                        ],
                        default="satis",
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("taslak", "Taslak"),
                            ("kesildi", "Kesildi"),
                            ("odendi", "Ödendi"),
                            ("iptal", "İptal"),
                        ],
                        default="taslak",
                        max_length=15,
                        verbose_name="Durum",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Fatura Tarihi")),
                (
                    "vade_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Vade Tarihi"),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama / Konu"
                    ),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faturalar",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-tarih", "-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="FaturaKalemi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sira",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Sıra"),
                ),
                (
                    "aciklama",
                    models.CharField(max_length=300, verbose_name="Açıklama / Hizmet"),
                ),
                (
                    "miktar",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "birim",
                    models.CharField(
                        default="Adet", max_length=20, verbose_name="Birim"
                    ),
                ),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "kdv_orani",
                    models.IntegerField(
                        choices=[
                            (0, "%0"),
                            (1, "%1"),
                            (8, "%8"),
                            (10, "%10"),
                            (20, "%20"),
                        ],
                        default=20,
                        verbose_name="KDV Oranı (%)",
                    ),
                ),
                (
                    "iskonto_oran",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="İskonto (%)",
                    ),
                ),
                (
                    "fatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalemler",
                        to="fatura.fatura",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Kalemi",
                "verbose_name_plural": "Fatura Kalemleri",
                "ordering": ["sira"],
            },
        ),
    ]
