# Generated by Django 5.2.12 on 2026-05-22 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="e_fatura_durum",
            field=models.CharField(
                choices=[
                    ("yok", "E-Fatura Değil"),
                    ("hazir", "XML Hazır"),
                    ("yuklendi", "GİB'e Yüklendi"),
                    ("onaylandi", "Onaylandı"),
                ],
                default="yok",
                max_length=15,
                verbose_name="E-Fatura Durumu",
            ),
        ),
        migrations.AddField(
            model_name="fatura",
            name="e_fatura_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="E-Fatura UUID",
            ),
        ),
    ]
