# Generated by Django 5.2.12 on 2026-05-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0002_fatura_e_fatura_durum_fatura_e_fatura_uuid"),
        ("stok", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturakalemi",
            name="urun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fatura_kalemleri",
                to="stok.urun",
                verbose_name="Ürün Kartı",
            ),
        ),
    ]
