# Generated by Django 5.2.12 on 2026-05-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0003_faturakalemi_urun"),
        ("stok", "0002_urun_degerleme_yontemi"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="odeme_yontemi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nakit", "Nakit"),
                    ("havale", "Havale / EFT"),
                    ("kredi_karti", "Kredi Kartı"),
                    ("cek", "Çek"),
                    ("diger", "Diğer"),
                ],
                default="havale",
                max_length=20,
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.AlterField(
            model_name="faturakalemi",
            name="urun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fatura_kalemleri",
                to="stok.urun",
                verbose_name="Ürün",
            ),
        ),
    ]
