# Generated by Django 6.0.2 on 2026-03-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sozlesme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "sozlesme_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sözleşme No"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("taslak", "Taslak"),
                            ("aktif", "Aktif"),
                            ("tamamlandi", "Tamamlandı"),
                            ("iptal", "İptal"),
                        ],
                        default="taslak",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "baslangic_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Sözleşme Tutarı",
                    ),
                ),
                (
                    "para_birimi",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        upload_to="sozlesmeler/",
                        verbose_name="Sözleşme Dosyası",
                    ),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sozlesmeler",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sözleşme",
                "verbose_name_plural": "Sözleşmeler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
