# Generated by Django 6.0.5 on 2026-05-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sync_motor", "0005_firmaayar_mikro_sunucu_uzak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAyar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_sunucu",
                    models.CharField(max_length=200, verbose_name="SMTP Sunucusu"),
                ),
                (
                    "smtp_port",
                    models.PositiveSmallIntegerField(
                        default=587, verbose_name="SMTP Port"
                    ),
                ),
                (
                    "kullanici",
                    models.EmailField(
                        max_length=254, verbose_name="Kullanıcı Adı (E-posta)"
                    ),
                ),
                (
                    "_sifre_sifreli",
                    models.TextField(
                        blank=True,
                        db_column="sifre_sifreli",
                        verbose_name="Şifre (Şifreli)",
                    ),
                ),
                (
                    "tls_kullan",
                    models.BooleanField(default=True, verbose_name="TLS Kullan"),
                ),
                (
                    "gonderen_ad",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Gönderici Adı"
                    ),
                ),
                (
                    "gonderen_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Gönderici E-posta"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("guncellendi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mail Ayarı",
                "verbose_name_plural": "Mail Ayarları",
                "ordering": ["-guncellendi"],
            },
        ),
        migrations.CreateModel(
            name="EkstreGonderimLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cari_kod", models.CharField(max_length=50, verbose_name="Cari Kodu")),
                (
                    "cari_unvan",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Cari Ünvanı"
                    ),
                ),
                (
                    "alici_email",
                    models.EmailField(max_length=254, verbose_name="Alıcı E-posta"),
                ),
                ("donem_baslangic", models.DateField(verbose_name="Dönem Başlangıcı")),
                ("donem_bitis", models.DateField(verbose_name="Dönem Bitişi")),
                (
                    "konu",
                    models.CharField(blank=True, max_length=300, verbose_name="Konu"),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[("gonderildi", "Gönderildi"), ("hata", "Hata")],
                        default="gonderildi",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "hata_mesaji",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sync_motor.firmaayar",
                        verbose_name="Firma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ekstre Gönderim Logu",
                "verbose_name_plural": "Ekstre Gönderim Logları",
                "ordering": ["-olusturuldu"],
            },
        ),
    ]
