# Generated by Django 6.0.5 on 2026-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekstregonderimlog",
            name="bilgi_email",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Bilgi (CC)"
            ),
        ),
        migrations.AlterField(
            model_name="ekstregonderimlog",
            name="alici_email",
            field=models.CharField(max_length=500, verbose_name="Alıcı (TO)"),
        ),
    ]
