# Generated by Django 5.2.14 on 2026-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posta", "0002_ekstregonderimlog_bilgi_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailayar",
            name="tls_dogrulamayi_atla",
            field=models.BooleanField(
                default=False,
                help_text="Yalnızca paylaşımlı/eski hosting sunucularında CERTIFICATE_VERIFY_FAILED hatası alındığında işaretleyin. Bağlantı şifreli kalır ancak sunucu kimliği doğrulanmaz.",
                verbose_name="TLS Sertifika Doğrulamasını Atla",
            ),
        ),
    ]
