# Generated by Django 6.0.5 on 2026-05-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sync_motor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MikroFatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fat_guid",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Mikro GUID"
                    ),
                ),
                (
                    "fat_evrak_seri",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Evrak Seri"
                    ),
                ),
                (
                    "fat_evrak_sira",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Evrak Sıra"
                    ),
                ),
                (
                    "fat_tarih",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fatura Tarihi"
                    ),
                ),
                (
                    "fat_vade_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Vade Tarihi"),
                ),
                (
                    "fat_cari_kod",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mikro Cari Kodu"
                    ),
                ),
                (
                    "fat_cari_unvan",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Cari Ünvanı"
                    ),
                ),
                (
                    "fat_cari_vkn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi No"
                    ),
                ),
                (
                    "fat_kdv_haric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="KDV Hariç",
                    ),
                ),
                (
                    "fat_kdv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="KDV Tutarı",
                    ),
                ),
                (
                    "fat_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Genel Toplam",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("alis", "Alış Faturası"),
                            ("satis", "Satış Faturası"),
                        ],
                        default="alis",
                        max_length=5,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("ham", "Ham — İşlenmedi"),
                            ("onay_bekliyor", "Onay Bekliyor"),
                            ("aktarildi", "Muhasebe Bürosu'na Aktarıldı"),
                            ("hata", "Hata"),
                            ("atla", "Atla"),
                        ],
                        default="ham",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("ham_json", models.TextField(blank=True, verbose_name="Ham JSON")),
                (
                    "mb_fatura_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Muhasebe Bürosu Fatura ID"
                    ),
                ),
                (
                    "mb_aktarim_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aktarım Tarihi"
                    ),
                ),
                (
                    "hata_mesaji",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mikro_faturalar",
                        to="sync_motor.firmaayar",
                    ),
                ),
                (
                    "import_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faturalar",
                        to="sync_motor.importlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mikro Fatura",
                "verbose_name_plural": "Mikro Faturalar",
                "ordering": ["-fat_tarih", "-olusturuldu"],
            },
        ),
        migrations.CreateModel(
            name="MikroCariHesap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cari_kod", models.CharField(max_length=50, verbose_name="Cari Kodu")),
                ("cari_unvan", models.CharField(max_length=300, verbose_name="Ünvanı")),
                (
                    "cari_vkn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi No"
                    ),
                ),
                (
                    "cari_telefon",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                (
                    "cari_email",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="E-posta"
                    ),
                ),
                (
                    "guncel_bakiye",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Güncel Bakiye",
                    ),
                ),
                ("son_guncelleme", models.DateTimeField(auto_now=True)),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cari_hesaplar",
                        to="sync_motor.firmaayar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mikro Cari Hesap",
                "verbose_name_plural": "Mikro Cari Hesaplar",
                "ordering": ["cari_unvan"],
                "unique_together": {("firma_ayar", "cari_kod")},
            },
        ),
        migrations.CreateModel(
            name="MikroStokKarti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stok_kod", models.CharField(max_length=50, verbose_name="Stok Kodu")),
                (
                    "stok_isim",
                    models.CharField(max_length=300, verbose_name="Stok İsmi"),
                ),
                (
                    "stok_birimi",
                    models.CharField(blank=True, max_length=20, verbose_name="Birimi"),
                ),
                (
                    "satis_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Satış Fiyatı",
                    ),
                ),
                ("son_guncelleme", models.DateTimeField(auto_now=True)),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stok_kartlari",
                        to="sync_motor.firmaayar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mikro Stok Kartı",
                "verbose_name_plural": "Mikro Stok Kartları",
                "ordering": ["stok_isim"],
                "unique_together": {("firma_ayar", "stok_kod")},
            },
        ),
    ]
