# Generated by Django 6.0.5 on 2026-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikro_gelen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mikrofatura",
            name="durum",
            field=models.CharField(
                choices=[
                    ("ham", "Ham — İşlenmedi"),
                    ("onay_bekliyor", "Onay Bekliyor"),
                    ("aktarildi", "Muhasebe Bürosu'na Aktarıldı"),
                    ("hata", "Hata"),
                    ("atla", "Atla"),
                ],
                db_index=True,
                default="ham",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="mikrofatura",
            name="fat_cari_kod",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Mikro Cari Kodu"
            ),
        ),
        migrations.AlterField(
            model_name="mikrofatura",
            name="fat_tarih",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Fatura Tarihi"
            ),
        ),
    ]
