# Generated by Django 6.0.5 on 2026-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikro_gelen", "0002_alter_mikrofatura_durum_and_more"),
        ("sync_motor", "0005_firmaayar_mikro_sunucu_uzak_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mikrofatura",
            unique_together={("firma_ayar", "fat_guid")},
        ),
        migrations.AlterField(
            model_name="mikrofatura",
            name="durum",
            field=models.CharField(
                choices=[
                    ("ham", "Ham — İşlenmedi"),
                    ("onay_bekliyor", "Onay Bekliyor"),
                    ("islendi", "İşlendi"),
                    ("hata", "Hata"),
                    ("atla", "Atla"),
                ],
                db_index=True,
                default="ham",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="mikrofatura",
            name="fat_guid",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Mikro GUID"
            ),
        ),
        migrations.RemoveField(
            model_name="mikrofatura",
            name="mb_aktarim_tarihi",
        ),
        migrations.RemoveField(
            model_name="mikrofatura",
            name="mb_fatura_id",
        ),
    ]
