# Generated by Django 6.0.5 on 2026-05-22 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmaAyar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Firma Adı")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "baglanti_tipi",
                    models.CharField(
                        choices=[
                            ("api", "Mikro API (port 8094)"),
                            ("sql", "SQL Server (direkt)"),
                            ("manuel", "Manuel XML Yükle"),
                        ],
                        default="api",
                        max_length=10,
                        verbose_name="Bağlantı Tipi",
                    ),
                ),
                (
                    "mikro_sunucu",
                    models.CharField(
                        blank=True,
                        help_text="örn: 192.168.1.10",
                        max_length=100,
                        verbose_name="Mikro Sunucu IP",
                    ),
                ),
                (
                    "mikro_port",
                    models.PositiveIntegerField(default=8094, verbose_name="API Port"),
                ),
                (
                    "mikro_kullanici",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mikro Kullanıcı"
                    ),
                ),
                (
                    "_mikro_sifre_sifreli",
                    models.TextField(blank=True, verbose_name="Şifreli Parola"),
                ),
                (
                    "sql_sunucu",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SQL Sunucu"
                    ),
                ),
                (
                    "sql_veritabani",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SQL Veritabanı"
                    ),
                ),
                (
                    "sql_kullanici",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SQL Kullanıcı"
                    ),
                ),
                (
                    "_sql_sifre_sifreli",
                    models.TextField(blank=True, verbose_name="SQL Şifreli Parola"),
                ),
                (
                    "mb_api_url",
                    models.CharField(
                        default="http://127.0.0.1:8000/api/v1/",
                        help_text="örn: http://127.0.0.1:8000/api/v1/",
                        max_length=200,
                        verbose_name="Muhasebe Bürosu API URL",
                    ),
                ),
                (
                    "mb_api_token",
                    models.TextField(
                        blank=True, verbose_name="Muhasebe Bürosu API Token"
                    ),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Firma Ayarı",
                "verbose_name_plural": "Firma Ayarları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yon",
                    models.CharField(
                        choices=[
                            ("mikro_to_mb", "Mikro → Muhasebe Bürosu"),
                            ("mb_to_mikro", "Muhasebe Bürosu → Mikro"),
                        ],
                        default="mikro_to_mb",
                        max_length=20,
                        verbose_name="Yön",
                    ),
                ),
                (
                    "baslangic_tarih",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "bitis_tarih",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("onay_bekliyor", "Onay Bekliyor"),
                            ("isleniyor", "İşleniyor"),
                            ("tamamlandi", "Tamamlandı"),
                            ("kismi", "Kısmi Başarı"),
                            ("hata", "Hata"),
                            ("iptal", "İptal"),
                        ],
                        default="beklemede",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "cekilen_adet",
                    models.IntegerField(default=0, verbose_name="Çekilen Kayıt"),
                ),
                (
                    "aktarilan_adet",
                    models.IntegerField(default=0, verbose_name="Aktarılan Kayıt"),
                ),
                (
                    "hata_adet",
                    models.IntegerField(default=0, verbose_name="Hatalı Kayıt"),
                ),
                (
                    "hata_detay",
                    models.TextField(blank=True, verbose_name="Hata Detayı"),
                ),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
                (
                    "baslayan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_loglari",
                        to="sync_motor.firmaayar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Logu",
                "verbose_name_plural": "Import Logları",
                "ordering": ["-olusturuldu"],
            },
        ),
        migrations.CreateModel(
            name="CariEslestirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mikro_cari_kod",
                    models.CharField(max_length=50, verbose_name="Mikro Cari Kodu"),
                ),
                (
                    "mikro_cari_unvan",
                    models.CharField(max_length=300, verbose_name="Mikro Cari Ünvanı"),
                ),
                (
                    "mb_cari_id",
                    models.IntegerField(verbose_name="Muhasebe Bürosu Cari ID"),
                ),
                (
                    "mb_cari_ad",
                    models.CharField(
                        max_length=300, verbose_name="Muhasebe Bürosu Cari Adı"
                    ),
                ),
                ("onay_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "guven_skoru",
                    models.FloatField(
                        default=1.0,
                        help_text="0.0-1.0 arası, 1.0=manuel onay",
                        verbose_name="Güven Skoru",
                    ),
                ),
                (
                    "onaylayan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cari_eslestirmeleri",
                        to="sync_motor.firmaayar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Eşleştirme",
                "verbose_name_plural": "Cari Eşleştirmeleri",
                "ordering": ["mikro_cari_unvan"],
                "unique_together": {("firma_ayar", "mikro_cari_kod")},
            },
        ),
        migrations.CreateModel(
            name="StokEslestirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mikro_stok_kod",
                    models.CharField(max_length=50, verbose_name="Mikro Stok Kodu"),
                ),
                (
                    "mikro_stok_isim",
                    models.CharField(max_length=300, verbose_name="Mikro Stok İsmi"),
                ),
                (
                    "mb_urun_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Muhasebe Bürosu Ürün ID"
                    ),
                ),
                (
                    "mb_urun_ad",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Muhasebe Bürosu Ürün Adı",
                    ),
                ),
                (
                    "yeni_urun_olustur",
                    models.BooleanField(
                        default=False, verbose_name="Yeni Ürün Oluştur"
                    ),
                ),
                ("onay_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "firma_ayar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stok_eslestirmeleri",
                        to="sync_motor.firmaayar",
                    ),
                ),
                (
                    "onaylayan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Eşleştirme",
                "verbose_name_plural": "Stok Eşleştirmeleri",
                "ordering": ["mikro_stok_isim"],
                "unique_together": {("firma_ayar", "mikro_stok_kod")},
            },
        ),
    ]
