# Generated by Django 6.0.5 on 2026-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_motor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmaayar",
            name="calisma_yili",
            field=models.CharField(
                default="2025",
                help_text="Örn: 2025",
                max_length=4,
                verbose_name="Çalışma Yılı",
            ),
        ),
        migrations.AddField(
            model_name="firmaayar",
            name="firma_kodu",
            field=models.CharField(
                blank=True,
                help_text="Mikro firma kodu (örn: MORE)",
                max_length=50,
                verbose_name="Firma Kodu",
            ),
        ),
        migrations.AddField(
            model_name="firmaayar",
            name="mikro_api_key",
            field=models.TextField(blank=True, verbose_name="Mikro API Key"),
        ),
    ]
