# Generated by Django 6.0.5 on 2026-05-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_motor", "0002_firmaayar_calisma_yili_firmaayar_firma_kodu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmaayar",
            name="mb_api_token",
        ),
        migrations.AddField(
            model_name="firmaayar",
            name="_mb_api_token_sifreli",
            field=models.TextField(blank=True, verbose_name="Şifreli MB Token"),
        ),
        migrations.AlterField(
            model_name="carieslestirme",
            name="firma_ayar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cari_eslestirmeleri",
                to="sync_motor.firmaayar",
            ),
        ),
    ]
