# Generated by Django 6.0.5 on 2026-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync_motor", "0003_remove_firmaayar_mb_api_token_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stokeslestirme",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="stokeslestirme",
            name="firma_ayar",
        ),
        migrations.RemoveField(
            model_name="stokeslestirme",
            name="onaylayan",
        ),
        migrations.RemoveField(
            model_name="firmaayar",
            name="_mb_api_token_sifreli",
        ),
        migrations.RemoveField(
            model_name="firmaayar",
            name="mb_api_url",
        ),
        migrations.RemoveField(
            model_name="importlog",
            name="yon",
        ),
        migrations.DeleteModel(
            name="CariEslestirme",
        ),
        migrations.DeleteModel(
            name="StokEslestirme",
        ),
    ]
