# Generated by Django 6.0.5 on 2026-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_motor", "0004_alter_stokeslestirme_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmaayar",
            name="mikro_sunucu_uzak",
            field=models.CharField(
                blank=True,
                help_text="RDP ile sunucudaysanız genellikle 127.0.0.1",
                max_length=100,
                verbose_name="Uzak Masaüstü IP",
            ),
        ),
        migrations.AddField(
            model_name="firmaayar",
            name="mikro_sunucu_vpn",
            field=models.CharField(
                blank=True,
                help_text="örn: 10.8.0.5",
                max_length=100,
                verbose_name="FortiClient VPN IP",
            ),
        ),
        migrations.AlterField(
            model_name="firmaayar",
            name="mikro_sunucu",
            field=models.CharField(
                blank=True,
                help_text="örn: 192.168.1.10",
                max_length=100,
                verbose_name="Yerel LAN IP",
            ),
        ),
    ]
